### PR TITLE
wolfSCP

### PR DESCRIPTION
**Pull request by ejohnstown**
Add support for an example SCP client.

### CODE REVIEW

**Comment by ejohnstown** [comment]
$ ./examples/echoserver/echoserver -d .
$ ./examples/scpclient/wolfscp -u jill -L ./test.txt:.

This will copy the file test.txt from the current directory to the echoserver's current directory. The paths need to be present in the commands. Note, if sending a larger file, you need to set the default window size larger.

**Comment by JacobBarthelmeh** [comment]
Hit a memory leak with the test case.

```
$ ./scripts/get-put.test 

=================================================================
==90682==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x1018767ef  (/usr/local/opt/gcc/lib/gcc/9/libasan.5.dylib:x86_64+0x7b7ef)
    #1 0x1015af263  (/Users/sweetness/Documents/wolfssh/src/.libs/libwolfssh.9.dylib:x86_64+0x3f263)
```

**Comment by JacobBarthelmeh** [comment]
Is rename of file currently not supported? i.e 

```
$ ./examples/scpclient/wolfscp -p 22 -H 192.168.1.149 -u pi2 -S /home/pi2/configure.ac:./new.ac
Password: 
wolfSSH error: Couldn't copy the file.
```

**Comment by ejohnstown** [comment]
I'm looking at the memory leak.

The rename isn't working. But, it isn't working without the PR using just wolfSCP server. I have this on the maintenance to-do list.

**Comment by ejohnstown** [comment]
I'm using commit 805034b of wolfSSL, configured with

    $ ./configure CC="clang -fsanitize=address" --enable-all --prefix=/opt/wolfssl-all --enable-static

and using the PR version of wolfSSH configured with:

    $ ./configure CC="clang -fsanitize=address" --enable-all LDFLAGS=-L/opt/wolfssl-all/lib CPPFLAGS=-I/opt/wolfssl-all/include --disable-shared

I run the test script and I'm not getting any reports. It also looks like that test case is SFTP only.

**Comment by JacobBarthelmeh** [comment]
I think the issues I'm reporting here are unrelated to the this PR. Am in the process of debugging them separately.

**Pull request merged**
