### PR TITLE
Add tests for scp, even empty file transfer.

### PR DESCRIPTION
**Pull request by anhu**

### CODE REVIEW

**Comment by anhu** [comment]
Self assigned because of failing tests.

**Comment by anhu** [comment]
Jenkins is failing on my tests.  But I don't understand why.  I can't repro on my local machine.  Tests pass fine.

**Review by ejohnstown — CHANGES_REQUESTED** [review]
I think you can assume touch is present if they are running the script in bash.

**Comment by anhu** [comment]
> I think you can assume touch is present if they are running the script in bash.

Will be done by Monday.

**Review by dgarske — APPROVED** [review]

**Review by ejohnstown — APPROVED** [review]

**Pull request merged**
